import Link from "next/link";
import { DEFAULT_WEIGHTS, PENALTY_ADVANTAGE_MULTIPLIER } from "@/config/scoring";
export default function MethodologyPage() {
  return <main>
    <header className="site-header"><Link className="brand" href="/">← DÖRT BÜYÜKLER ENDEKSİ</Link></header>
    <article className="doc"><p className="eyebrow">METODOLOJİ</p><h1>Şeffaf, yeniden hesaplanabilir ölçüm</h1>
      <section><h2>Yalnızca karar etkisi</h2><p>Maç kazanmak, skor, fikstür güçlüğü, kadro metriği veya hakem gözlemci puanı endekse katkı sağlamaz. Pozitif skor kasıtlı kayırma, negatif skor kasıtlı mağduriyet kanıtı değildir.</p></section>
      <section><h2>Ceza etkisi</h2><p>Normal sarı kart puanlanmaz. Kırmızı, ikinci sarı veya sarı kart birikiminin önemli maçta ceza infazına neden olduğu kaynakla doğrulanmalıdır. Kadroda bulunmama tek başına ceza kanıtı değildir. Kupa infazı ve çok maçlık cezalar için etkilenen maç kimlikleri ayrıca kaydedilir.</p><p>Tüm lig takımları araştırılır. Cezalı oyuncunun takımı dört büyükten biriyse ve önemli rakibi diğer dört büyüklerden biriyse kendi dezavantajı yazılır; rakip hangi takım olursa olsun dört büyüklerden biriyle karşılaşırken önemli cezalı oyuncusu varsa o büyük takıma dolaylı avantaj yazılır.</p><p>Sonraki maç hafta numarasıyla değil gerçek oynanma tarihiyle belirlenir. Tarihi bilinmeyen kayıt için sonraki maç tahmin edilmez.</p><code>hamCezaEtkisi = normalize(bağımsızOyuncuPuanı) × 2,25</code><p>Oyuncu puanı, ölçeği, değerli oyuncu eşiği, değerlendirme tarihi ve kaynak bağlantısı JSON&apos;da saklanır. Puanın kart maçından sonra alınmasına izin verilmez. İlk 11/gol temelli yerel tahmin kaldırılmıştır. FotMob için kart öncesindeki son beş puanlanan lig maçının ortalaması kullanılır; en az üç puan gerekir. Ortak model önem eşiği 7/10’dur. Bu eşik açık bir model varsayımıdır; sezon sonu puanları geçmişe uygulanmaz.</p></section>
      <section><h2>Penaltı kararı, penaltı golü değildir</h2><p>Verilen penaltı için ham etki 1&apos;dir; gol, kaçırma veya kurtarılma aynı puanı alır. Lehe penaltı katkısına ×{PENALTY_ADVANTAGE_MULTIPLIER} çarpanı uygulanır; aleyhe penaltı katkısı değişmez. Genel endekste bir lehe penaltı +0,02, bir aleyhe penaltı −0,08 puandır (güven 1 için). Önceki 0,50 çarpanı %50 daha azaltılarak 0,25 olmuştur; başlangıç ağırlığına göre toplam indirim %75’tir. Daha fazla hücum/topla oynama isteğinin penaltı kazanma sayısıyla bağlantılı olabileceği düşüncesiyle lehe katkı azaltılmıştır. Bu indirim model tercihidir; gerçek topla oynama verisiyle hesaplanmış bir düzeltme veya hakem hatası ölçümü değildir. Penaltıların iki karşı kaydı eşit büyüklükte değildir.</p><p>TFF gol listesine Transfermarkt’ın üç sezonluk kaçan penaltı envanteri eklenmiştir. Kayıtlar TFF maç kimliğiyle eşleştirilir ve FotMob maç olaylarıyla karşılaştırılır. Tatil edilen maçta verilmiş Morata penaltısı resmî Galatasaray maç raporuyla ayrıca kaydedilmiştir; hükmen maç sonucu puana etki etmez.</p></section>
      <section><h2>Ağırlıklar ve karşı kayıt</h2><code>etki = hamEtki × güven × kategoriAğırlığı × yönÇarpanı × genelÇarpan</code><p>Genel görünümde tüm hakem etkilerine aynı 0,40 çarpanı uygulanır; hakem görünümünde genel çarpan 1&apos;dir. Kritik ceza taban ağırlığı 0,35, penaltı ve VAR ağırlığı 0,20&apos;dir. Rakip eksikliği avantajı ve kart-ceza dezavantajı için önceki 1,30 çarpanı %50 artırılarak 1,95 olmuştur; başlangıca göre toplam artış %95’tir. Her ikisinin etkin kategori ağırlığı 0,6825 olur. Her katkıya 1,95 çarpanı bir kez uygulanır; avantaj ve dezavantaj çarpanları birbirine uygulanmaz. Aynı cezanın karşı kayıtları eşit büyüklüktedir. Lehe penaltı yön çarpanı 0,25, diğer etkilerinki 1&apos;dir. Normal kartlar ve doğrulanmamış ceza adayları puanlanmaz.</p><pre>{JSON.stringify(DEFAULT_WEIGHTS.referee, null, 2)}</pre><p>Ağırlıklar model varsayımıdır; bilimsel sabit değildir. DISCIPLINE normal kartlar için uygulanmaz.</p></section>
      <section><h2>Eksik veri, sıralama ve duyarlılık</h2><p>Doğrulanmamış olay puanlanmaz. Doğrulanmış kayıt yoksa değer null&apos;dır: “—” sıfır anlamına gelmez. İncelenmiş kayıtlar kısmi toplam verir; kategori kapsamı tamamlanmadan kesin sıralama gösterilmez. Eksik olayların etkisi bilinmediğinden istatistiksel güven aralığı üretilmez.</p><p>Duyarlılık, aynı kategori içindeki imzalı katkılar netleştirildikten sonra kategori ağırlıklarının birbirinden bağımsız ±%20 değişiminin en kötü durum etkisidir. Kayıt güveni eksik veri kapsamı anlamına gelmez.</p></section>
      <section><h2>Kaynaklı JSON giriş</h2><p>İncelenmiş kayıtlar data/raw/reviewed-decisions.json dosyasından şema kontrolüyle yüklenir. Ceza infazı, bağımsız oyuncu puanı veya penaltı karar kaynağı eksikse kayıt doğrulanmış sayılmaz. Penaltı envanteri ve incelenmiş ceza kayıtları yüklüdür. Henüz infazı/itiraz sonucu incelenmemiş ceza adayları ayrı JSON’da tutulur ve puanlanmaz.</p><p><a href="https://www.tff.org/Resources/TFF/Documents/TALIMATLAR/Futbol-Disiplin-Talimati.pdf" target="_blank" rel="noreferrer">TFF Futbol Disiplin Talimatı ↗</a>: dördün katındaki sarı kart sayımı yalnızca araştırma adayı üretir; sezon statüsü, iptaller ve eksik kart geçmişi ayrıca kontrol edilmelidir.</p></section>
    </article>
  </main>;
}
