import type { ScoringWeights } from "@/schemas/domain";

export const DEFAULT_WEIGHTS: ScoringWeights = {
  referee: { DISCIPLINE: .25, CRITICAL_SUSPENSION: .25, PENALTIES: .20, VAR: .20, OTHER_REFEREE: .10 },
  general: { REFEREE: .40, OPPONENT_AVAILABILITY: .20, INJURIES: .15, SCHEDULE: .10, OPPONENT_STRENGTH: .10, OTHER: .05 },
};

export const REQUIRED_REFEREE_CATEGORIES = ["DISCIPLINE", "CRITICAL_SUSPENSION", "PENALTIES", "VAR"] as const;
export const REQUIRED_GENERAL_CATEGORIES = ["INJURIES", "SCHEDULE", "OPPONENT_AVAILABILITY", "OPPONENT_STRENGTH"] as const;
