"use client";
import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { importedMatches, datasetGeneratedAt } from "@/data/matches";
import { teams } from "@/data/teams";
import { ledgerEvents } from "@/data/ledger";

const cardRows = importedMatches.flatMap((match) => (match.details?.cards ?? []).map((card, index) => ({ ...card, id: `${match.matchId}-${index}`, season: match.season, week: match.week, matchId: match.matchId, match: `${match.homeTeam.sourceName} - ${match.awayTeam.sourceName}`, detailUrl: match.detailUrl })));
const officialRows = importedMatches.flatMap((match) => (match.details?.officials ?? []).map((official, index) => ({ ...official, id: `${match.matchId}-${index}`, season: match.season, week: match.week, matchId: match.matchId, match: `${match.homeTeam.sourceName} - ${match.awayTeam.sourceName}`, detailUrl: match.detailUrl })));

export function DataExplorer(){
  const params = useSearchParams();
  const rawCategory = params.get("category") ?? "Maçlar";
  const eventCategoryMap: Record<string,string> = { "Penaltı golleri": "PENALTY", "Dinlenme / fikstür": "SCHEDULE", "Rakip gücü": "OPPONENT_STRENGTH", "Kart sonrası eksikler": "SUSPENSION", "Kritik cezalar": "SUSPENSION", "Rakip eksikleri": "SUSPENSION", "Kadro mevcudiyeti": "INJURY" };
  const category = rawCategory === "Oyuncu kartları" ? "Kartlar" : rawCategory === "VAR görevlendirmeleri" ? "Hakemler" : eventCategoryMap[rawCategory] ? "Endeks olayları" : rawCategory;
  const season = params.get("season") ?? "all";
  const team = params.get("team") ?? "all";
  const url = (updates: Record<string,string>) => { const next = new URLSearchParams(params.toString()); for (const [key,val] of Object.entries(updates)) { if (val === "all") next.delete(key); else next.set(key,val); } return `/data?${next.toString()}`; };
  const matches = importedMatches.filter((match) => (season === "all" || match.season === season) && (team === "all" || match.homeTeam.teamId === team || match.awayTeam.teamId === team));
  const cards = cardRows.filter((row) => (season === "all" || row.season === season) && (team === "all" || row.teamId === team));
  const officials = officialRows.filter((row) => season === "all" || row.season === season);
  const eventType = eventCategoryMap[rawCategory];
  const events = ledgerEvents.filter((event) => !event.isMock && (!eventType || event.eventType === eventType) && (season === "all" || event.season === season) && (team === "all" || event.effects.some((effect) => effect.teamId === team)));
  return <main><header className="site-header"><Link className="brand" href="/">← DÖRT BÜYÜKLER ENDEKSİ</Link></header><article className="doc wide"><p className="eyebrow">REPO-OWNED HAM VERİ</p><h1>Veri Gezgini</h1><div className="import-summary"><b>{importedMatches.length} maç · {cardRows.length} kart olayı</b><span>3 sezon · TFF resmî verileri</span><small>{new Date(datasetGeneratedAt).toLocaleString("tr-TR")}</small></div><div className="explorer-tabs">{["Maçlar","Kartlar","Hakemler","Endeks olayları"].map((item)=><Link className={category===item?"active":""} key={item} href={url({category:item})}>{item}</Link>)}</div><div className="data-filters"><label>Sezon <select value={season} onChange={(event)=>location.href=url({season:event.target.value})}><option value="all">Tümü</option><option>2023-24</option><option>2024-25</option><option>2025-26</option></select></label><label>Takım <select value={team} onChange={(event)=>location.href=url({team:event.target.value})}><option value="all">Tümü</option>{teams.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label></div>
  {category === "Kartlar" && <><h2>Kart olayları <span className="count">{cards.length}</span></h2><div className="table-scroll"><table className="explorer"><thead><tr><th>Sezon</th><th>H.</th><th>Maç</th><th>Takım</th><th>Oyuncu</th><th>Tür</th><th>Dakika</th><th>TFF</th></tr></thead><tbody>{cards.slice(0,300).map((row)=><tr key={row.id}><td>{row.season}</td><td>{row.week}</td><td>{row.match}</td><td>{teams.find((item)=>item.id===row.teamId)?.shortName ?? row.tffClubId}</td><td><b>{row.player}</b></td><td><span className={`card-type ${row.type}`}>{row.type}</span></td><td>{row.minute ?? "—"}</td><td><a href={row.detailUrl} target="_blank" rel="noreferrer">{row.matchId}</a></td></tr>)}</tbody></table></div><p className="table-note">İlk 300 kayıt gösteriliyor; filtre sayısı ve JSON toplamı yukarıda eksiksiz hesaplanır.</p></>}
  {category === "Hakemler" && <><h2>Hakem görevlileri <span className="count">{officials.length}</span></h2><div className="table-scroll"><table className="explorer"><thead><tr><th>Sezon</th><th>H.</th><th>Maç</th><th>Görev</th><th>Hakem</th><th>TFF ID</th><th>Kaynak</th></tr></thead><tbody>{officials.slice(0,300).map((row)=><tr key={row.id}><td>{row.season}</td><td>{row.week}</td><td>{row.match}</td><td>{row.role}</td><td><b>{row.name}</b></td><td>{row.tffPersonId}</td><td><a href={row.detailUrl} target="_blank" rel="noreferrer">{row.matchId}</a></td></tr>)}</tbody></table></div></>}
  {category === "Endeks olayları" && <><h2>{rawCategory === "Endeks olayları" ? "Endeks olayları" : rawCategory} <span className="count">{events.length}</span></h2><div className="table-scroll"><table className="explorer"><thead><tr><th>Sezon</th><th>Tür</th><th>Maç</th><th>Takım</th><th>Yön</th><th>Ham etki</th><th>Açıklama</th><th>Kalite</th></tr></thead><tbody>{events.slice(0,300).flatMap((event) => event.effects.filter((effect) => team === "all" || effect.teamId === team).map((effect) => <tr key={`${event.eventId}-${effect.teamId}`}><td>{event.season}</td><td>{event.eventType}</td><td>{event.matchLabel}</td><td>{teams.find((item)=>item.id===effect.teamId)?.name}</td><td>{effect.direction}</td><td>{effect.rawImpact.toFixed(2)}</td><td>{effect.explanation}</td><td><span className="verified-pill">{event.quality}</span></td></tr>))}</tbody></table></div></>}
  {category === "Maçlar" && <><h2>Maçlar <span className="count">{matches.length}</span></h2><div className="table-scroll"><table className="explorer"><thead><tr><th>Sezon</th><th>H.</th><th>Ev sahibi</th><th>Skor</th><th>Deplasman</th><th>TFF Match ID</th><th>Detay</th></tr></thead><tbody>{matches.slice(0,200).map((match)=><tr key={match.matchId}><td>{match.season}</td><td>{match.week}</td><td>{match.homeTeam.sourceName}</td><td><b>{match.score.home} - {match.score.away}</b></td><td>{match.awayTeam.sourceName}</td><td>{match.matchId}</td><td>{match.details ? <span className="verified-pill">VERIFIED</span> : <span>Eksik</span>}</td></tr>)}</tbody></table></div></>}
  </article></main>;
}
