"use client";
import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { importedMatches, datasetGeneratedAt } from "@/data/matches";
import { formatScore } from "@/scoring/presentation";
import { teams } from "@/data/teams";
import { ledgerEvents } from "@/data/ledger";
import { scoreContributions, isScorableEvent } from "@/scoring/engine";

const cardRows = importedMatches.flatMap((match) => (match.details?.cards ?? []).map((card, index) => ({ ...card, id: `${match.matchId}-${index}`, season: match.season, week: match.week, matchId: match.matchId, match: `${match.homeTeam.sourceName} - ${match.awayTeam.sourceName}`, detailUrl: match.detailUrl })));
const officialRows = importedMatches.flatMap((match) => (match.details?.officials ?? []).map((official, index) => ({ ...official, id: `${match.matchId}-${index}`, season: match.season, week: match.week, matchId: match.matchId, match: `${match.homeTeam.sourceName} - ${match.awayTeam.sourceName}`, detailUrl: match.detailUrl })));

export function DataExplorer(){
  const params = useSearchParams();
  const rawCategory = params.get("category") ?? "Maçlar";
  const eventCategoryMap: Record<string,string> = { "Penaltı golleri": "PENALTY", "Kart sonrası eksikler": "SUSPENSION", "Kritik cezalar": "SUSPENSION", "Rakip eksikleri": "SUSPENSION" };
  const category = (rawCategory === "Oyuncu kartları" || rawCategory === "Kart kayıtları") ? "Kartlar" : rawCategory === "VAR görevlendirmeleri" ? "Hakemler" : eventCategoryMap[rawCategory] ? "Endeks olayları" : rawCategory;
  const season = params.get("season") ?? "all";
  const team = params.get("team") ?? "all";
  const url = (updates: Record<string,string>) => { const next = new URLSearchParams(params.toString()); if (!("page" in updates)) next.delete("page"); for (const [key,val] of Object.entries(updates)) { if (val === "all") next.delete(key); else next.set(key,val); } return `/data?${next.toString()}`; };
  const matches = importedMatches.filter((match) => (season === "all" || match.season === season) && (team === "all" || match.homeTeam.teamId === team || match.awayTeam.teamId === team));
  const cards = cardRows.filter((row) => (season === "all" || row.season === season) && (team === "all" || row.teamId === team));
  const matchIds = new Set(matches.map((match) => match.matchId));
  const officials = officialRows.filter((row) => matchIds.has(row.matchId));
  const eventType = eventCategoryMap[rawCategory];
  const relevantEffect = (effect: (typeof ledgerEvents)[number]["effects"][number]) => (team === "all" || effect.teamId === team) && (rawCategory !== "Kritik cezalar" || effect.category === "CRITICAL_SUSPENSION") && (rawCategory !== "Rakip eksikleri" || effect.category === "OPPONENT_AVAILABILITY");
  const events = ledgerEvents.filter((event) => isScorableEvent(event) && (!eventType || event.eventType === eventType) && (season === "all" || event.season === season) && event.effects.some(relevantEffect));
  const pageSize = 100;
  const total = category === "Kartlar" ? cards.length : category === "Hakemler" ? officials.length : category === "Endeks olayları" ? events.length : matches.length;
  const pageCount = Math.max(1, Math.ceil(total / pageSize));
  const requestedPage = Number(params.get("page") ?? 1);
  const page = Math.min(pageCount, Math.max(1, Number.isFinite(requestedPage) ? Math.floor(requestedPage) : 1));
  const start = (page - 1) * pageSize;
  const pageRows = <div className="pagination"><span>{total ? `${start + 1}–${Math.min(start + pageSize, total)} / ${total} kayıt` : "Bu filtrelere uygun kayıt bulunamadı."} · Sayfa {page} / {pageCount}</span>{page > 1 && <Link className="outline" href={url({page: String(page - 1)})}>← Önceki</Link>}{page < pageCount && <Link className="outline" href={url({page: String(page + 1)})}>Sonraki →</Link>}</div>;
  return <main><header className="site-header"><Link className="brand" href="/">← DÖRT BÜYÜKLER ENDEKSİ</Link></header><article className="doc wide"><p className="eyebrow">KAYNAKLARIYLA BİRLİKTE</p><h1>Maç ve olay kayıtları</h1><p>Endeks olaylarında yalnızca doğrulanıp hesaba katılan kayıtlar gösterilir. İnceleme bekleyen veriler arşivde tutulur.</p><div className="import-summary"><b>{importedMatches.length} maç · {cardRows.length} kart olayı</b><span>Üç sezonun kayıtları · ceza ve VAR araştırması henüz tamamlanmadı</span><small>{new Date(datasetGeneratedAt).toLocaleString("tr-TR")}</small></div><div className="explorer-tabs">{["Maçlar","Kartlar","Hakemler","Endeks olayları"].map((item)=><Link className={category===item?"active":""} key={item} href={url({category:item})}>{item}</Link>)}</div><div className="data-filters"><label>Sezon <select value={season} onChange={(event)=>location.href=url({season:event.target.value})}><option value="all">Tümü</option><option>2023-24</option><option>2024-25</option><option>2025-26</option></select></label><label>Takım <select value={team} onChange={(event)=>location.href=url({team:event.target.value})}><option value="all">Tümü</option>{teams.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label></div>
  {category === "Kartlar" && <><h2>Kart olayları <span className="count">{cards.length}</span></h2><div className="table-scroll"><table className="explorer"><thead><tr><th>Sezon</th><th>Hafta</th><th>Maç</th><th>Takım</th><th>Oyuncu</th><th>Tür</th><th>Dakika</th><th>TFF</th></tr></thead><tbody>{cards.slice(start, start + pageSize).map((row)=><tr key={row.id}><td>{row.season}</td><td>{row.week}</td><td>{row.match}</td><td>{teams.find((item)=>item.id===row.teamId)?.shortName ?? row.tffClubId}</td><td><b>{row.player}</b></td><td><span className={`card-type ${row.type}`}>{row.type === "yellow" ? "Sarı kart" : row.type === "second_yellow" ? "İkinci sarı" : "Kırmızı kart"}</span></td><td>{row.minute ?? "—"}</td><td><a href={row.detailUrl} target="_blank" rel="noreferrer">{row.matchId}</a></td></tr>)}</tbody></table></div><p className="table-note">Tüm kayıtlara aşağıdaki sayfa bağlantılarıyla ulaşabilirsiniz.</p></>}
  {category === "Hakemler" && <><h2>Hakem görevlileri <span className="count">{officials.length}</span></h2><div className="table-scroll"><table className="explorer"><thead><tr><th>Sezon</th><th>Hafta</th><th>Maç</th><th>Görev</th><th>Hakem</th><th>TFF kayıt no.</th><th>Kaynak</th></tr></thead><tbody>{officials.slice(start, start + pageSize).map((row)=><tr key={row.id}><td>{row.season}</td><td>{row.week}</td><td>{row.match}</td><td>{row.role}</td><td><b>{row.name}</b></td><td>{row.tffPersonId}</td><td><a href={row.detailUrl} target="_blank" rel="noreferrer">{row.matchId}</a></td></tr>)}</tbody></table></div></>}
  {category === "Endeks olayları" && <><h2>{rawCategory === "Endeks olayları" ? "Endeks olayları" : rawCategory} <span className="count">{events.length}</span></h2><div className="table-scroll"><table className="explorer"><thead><tr><th>Sezon</th><th>Tür</th><th>Maç</th><th>Takım</th><th>Yön</th><th>Puan katkısı</th><th>Açıklama</th><th>İnceleme durumu</th><th>Kaynaklar</th></tr></thead><tbody>{events.slice(start, start + pageSize).flatMap((event) => event.effects.filter(relevantEffect).map((effect) => <tr key={`${event.eventId}-${effect.teamId}`}><td>{event.season}</td><td>{event.eventType === "PENALTY" ? "Penaltı" : event.eventType === "SUSPENSION" ? "Ceza" : event.eventType === "CARD" ? "Kart" : "Diğer"}</td><td>{event.matchLabel}</td><td>{teams.find((item)=>item.id===effect.teamId)?.name}</td><td>{effect.direction === "advantage" ? "Avantaj" : "Dezavantaj"}</td><td>{isScorableEvent(event) ? formatScore((effect.direction === "disadvantage" ? -1 : 1) * (scoreContributions([event], effect.teamId, "general").find((c) => c.category === effect.category)?.amount ?? 0)) : "—"}</td><td>{effect.explanation}</td><td><span className="verified-pill">{isScorableEvent(event) ? "Doğrulandı" : "İnceleme bekliyor"}</span><p>{isScorableEvent(event) ? "Dahil" : "Doğrulama bekliyor · puanlanmadı"}</p></td><td>{event.sourceIds.map((url) => <a key={url} href={url} target="_blank" rel="noreferrer">Kaynak ↗ </a>)}</td></tr>))}</tbody></table></div></>}
  {category === "Maçlar" && <><h2>Maçlar <span className="count">{matches.length}</span></h2><div className="table-scroll"><table className="explorer"><thead><tr><th>Sezon</th><th>Hafta</th><th>Ev sahibi</th><th>Skor</th><th>Deplasman</th><th>Maç kayıt no.</th><th>Detay</th></tr></thead><tbody>{matches.slice(start, start + pageSize).map((match)=><tr key={match.matchId}><td>{match.season}</td><td>{match.week}</td><td>{match.homeTeam.sourceName}</td><td><b>{match.score.home ?? "—"} - {match.score.away ?? "—"}</b></td><td>{match.awayTeam.sourceName}</td><td>{match.matchId}</td><td>{match.details ? <span className="verified-pill">Doğrulandı</span> : <span>Eksik</span>}</td></tr>)}</tbody></table></div></>}
  {pageRows}
  </article></main>;
}
