import Link from "next/link";
import catalog from "../../../data/normalized/evidence-sources.json";
import { importedMatches } from "@/data/matches";
import { ledgerEvents } from "@/data/ledger";
import { isScorableEvent } from "@/scoring/engine";

const fixtureSources = { "2023-24": "https://www.tff.org/Default.aspx?pageID=1648", "2024-25": "https://www.tff.org/Default.aspx?pageID=1730", "2025-26": "https://www.tff.org/Default.aspx?pageID=1768" } as const;
const seasons = ["2023-24", "2024-25", "2025-26"] as const;

export default function SourcesPage() {
  return <main>
    <header className="site-header"><Link className="brand" href="/">← DÖRT BÜYÜKLER ENDEKSİ</Link><nav><Link href="/">Ana sayfa</Link><Link href="/data">Veri gezgini</Link><Link href="/methodology">Metodoloji</Link></nav></header>
    <article className="doc wide">
      <p className="eyebrow">KAYNAK ŞEFFAFLIĞI</p><h1>Tüm veri kaynakları</h1>
      <div className="notice"><div><b>Birincil kaynak: Türkiye Futbol Federasyonu</b><p>Aşağıdaki bağlantılar, endekste kullanılan her ham maç kaydının TFF sayfasına birebir gider. Ceza kararları için PFDK, oyuncu puanları için FotMob, kaçan penaltılar için Transfermarkt kullanılır. Her sağlayıcının bağlantıları aşağıdadır.</p></div></div>
      <h2>Sezon fikstür kaynakları</h2>
      <div className="source-grid">{seasons.map((season) => { const matches = importedMatches.filter((match) => match.season === season); return <a key={season} className="source-card" href={fixtureSources[season]} target="_blank" rel="noreferrer"><b>{season} Süper Lig fikstürü</b><span>TFF resmî fikstür ve sonuç sayfası</span><small>{matches.length} endeks maçı · TFF&apos;de aç →</small></a>; })}</div>
      <h2>Maç bazında birebir kaynaklar</h2><p>Her bağlantı; tarih, skor, hakem/VAR kadrosu, kartlar, goller, ilk 11 ve yedekler için kullanılan TFF maç detayına açılır.</p>
      {seasons.map((season) => <section key={season} className="source-season"><h3>{season} <span className="verified-pill">{importedMatches.filter((match) => match.season === season).length} MAÇ</span></h3><div className="table-scroll"><table className="explorer source-table"><thead><tr><th>Hafta</th><th>Maç</th><th>Skor</th><th>TFF maç kaynağı</th></tr></thead><tbody>{importedMatches.filter((match) => match.season === season).sort((a, b) => a.week - b.week || a.matchId.localeCompare(b.matchId)).map((match) => <tr key={match.matchId}><td>{match.week}</td><td>{match.homeTeam.sourceName} – {match.awayTeam.sourceName}</td><td>{match.score.home} - {match.score.away}</td><td><a href={match.detailUrl} target="_blank" rel="noreferrer">TFF maç detayı ↗</a></td></tr>)}</tbody></table></div></section>)}
      <h2>İncelenmiş karar kayıtları</h2><p>Kaynak URL&apos;leriyle doğrulanan penaltı ve ceza kayıtları <code>data/raw/reviewed-decisions.json</code> dosyasından yüklenir. Envanterde {catalog.counts.penalties} penaltı kararı ve {catalog.counts.reviewedSuspensions} incelenmiş ceza bulunur. Ceza infazı/itiraz kapsamı eksik olduğundan kesin sıralama iddiası yoktur.</p><ul>{ledgerEvents.filter(isScorableEvent).map((event) => <li key={event.eventId}>{event.matchLabel} · {event.eventType}: {event.sourceIds.map((url) => <a key={url} href={url} target="_blank" rel="noreferrer">Kaynak ↗ </a>)}</li>)}</ul><h2>Araştırma adayları</h2><ul><li>TFF&apos;de `(P)` işaretli gol olmuş penaltılar ve Transfermarkt kaçan penaltıları aynı sabit karar puanını alır. Maçın tatil edildiği Morata penaltısı ayrıca kulüp kaynağıyla doğrulanmıştır.</li><li>Tarih sırasıyla kırmızı/ikinci sarı ve sarı birikimi sonrası kadroda yokluk, ceza araştırma adayıdır; tek başına ceza kanıtı değildir</li><li>Bu endekste fikstür, rakip gücü ve maç kazanma etkisi kullanılmaz.</li></ul>
      <h2>Ücretsiz oyuncu puanı kaynakları</h2><p>{catalog.counts.ratedAppearances.toLocaleString("tr-TR")} maç bazlı oyuncu puanı arşivlendi. Sezon sonu ortalamaları geçmiş maçlara uygulanmaz.</p><ul>{catalog.ratingSources.map((source) => <li key={source.season}><a href={source.url} target="_blank" rel="noreferrer">{source.season} FotMob oyuncu puanları ↗</a> · {source.records} oyuncu</li>)}</ul><details><summary>{catalog.matchSources.length} maçın birebir FotMob kaynakları</summary><ul>{catalog.matchSources.map((source) => <li key={source.matchId}>{source.season} · TFF {source.matchId}: <a href={source.pageUrl} target="_blank" rel="noreferrer">Maç sayfası ↗</a> · <a href={source.url} target="_blank" rel="noreferrer">Ham puan/olay JSON ↗</a></li>)}</ul></details><h2>Resmî disiplin kaynakları</h2><p>Oyuncu adının kararda bulunması infazı veya cezanın sonradan değişmediğini tek başına kanıtlamaz.</p><details><summary>{catalog.courtSources.length} PFDK belgesini göster</summary><ul>{catalog.courtSources.map((source) => <li key={source.url}><a href={source.url} target="_blank" rel="noreferrer">{source.title} ↗</a> · {source.matchedPlayers} oyuncu eşleşmesi</li>)}</ul></details><h2>Doğrulama sınırları</h2><ul><li>Kadroda bulunmamak tek başına sakatlık sayılmaz; tıbbi neden iddia edilmez.</li><li>VAR görevlendirmesi kaydedilir; kararın doğru veya yanlış olduğu iddia edilmez.</li><li>Kesin ceza infazı için maçla eşleştirilebilir PFDK veya resmî ceza kaydı; oyuncu önemi için bağımsız, maç öncesi tarihli puan kaynağı gerekir.</li></ul><p>Ham JSON kopyaları, erişim zamanı, kayıt sayısı ve SHA-256 özetiyle repoda <code>data/sources-manifest.json</code> altında saklanır.</p>
    </article>
  </main>;
}
